version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    container_name: testaws
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx.dev:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network
  database:
    image: postgres
    container_name: database
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    networks:
      - app-network
volumes:
  postgres:
    external: true

networks:
  app-network:
    driver: bridge
